### ISSUE TITLE
Add support to retrieve repo information from environment variable 

### ISSUE THREAD

**Issue by hjkwok** [gitparent/gitparent#26]
For CI / automated system, adding support to retrieve repo information, such as repo path, username and password if that was set in the environment can help simplifying  CI complexity.

**Comment by junechanh** [comment]
Going to implement this like so:

- Enable environment variable interpolation within .gitp_manifest by adding a `variables` section that specifies default values for said variables which are overridden by environment variables, if they are set).
- Add optional user/password (or token) entries. Parse repo urls to automatically extract this info if it is supplied.

**Comment by junechanh** [comment]
Implemented in 20220727 release.

**Comment by junechanh** [comment]
Note that env var interpolation will be slightly more restrictive after this release -- suggest explicitly listing out all interpolated env vars in the manifest to support this future behavior (https://github.com/gitparent/gitparent/commit/fb92ca91cb8145b376db028b927a4b2839520dce)
