### ISSUE TITLE
Wrong git repo access path assemble from environment var

### ISSUE THREAD

**Issue by hjkwok** [gitparent/gitparent#27]
After enabling #26, the repo is wrongly assemble from environment var. Result in an un-reachable repo situation in CI. 

For example
in .gitp_manifest
repos:
   some_repo:
      url: gitlab.xxx.xxx:abce/some/repo.git
      username: ${GITLAB_USERNAME}
      password: ${GITLAB_PASSWORD}
variables:
   GITLAB_USERNAME: git #default to 'git' user
   GITLAB_PASSWORD: #default to nothing

in CI 

$GITLAB_USERNAME: some_user
$GITLAB_PASSWORD: some_pwd

the following error occur in CI execution 

ssh: Could not resolve hostname some_user: Name or service not known

**Comment by junechanh** [comment]
Thanks. I forgot that you can't specify a password in SSH URLs. I'm going to enhance gitparent to differentiate between ssh and http(s) URLs and have it so the `password` field of repo entries only applies to the former. May add a switch to allow user to explicitly specify one of the two on `sync` and `pull`. Whatever is passed in on `new` will be the default.
